CREATE TABLE IF NOT EXISTS feedback (
  id SERIAL PRIMARY KEY,
  username VARCHAR(250) NOT NULL REFERENCES users(username) ON DELETE CASCADE,
  text TEXT NOT NULL,
  stars INTEGER NOT NULL CHECK (stars BETWEEN 1 AND 5),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS feedback_username_idx ON feedback(username);
